# Generated by Django 5.0.7 on 2024-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level0design',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='level0design',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
