# Generated by Django 5.0.7 on 2024-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_name',
            field=models.TextField(default=''),
        ),
    ]
