# Generated by Django 5.0.7 on 2024-08-21 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level1Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(default='')),
                ('module_name', models.TextField(default='')),
                ('inputs', models.JSONField(default=list)),
                ('outputs', models.JSONField(default=list)),
                ('functionality', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('time', models.TextField(default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
