# Generated by Django 5.0.7 on 2024-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_level0design_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level0design',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='level0design',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
